#import "LCProxyConfig.h"
#import "LCProxyPaths.h"
#import "lcproxy_bridge.h"
#import "LCProxyKing.h"

static NSString *const LCProxySettingsFile = @"settings.json";
static NSString *const LCProxyConfFile = @"proxychains.conf";

@implementation LCProxyConfig

+ (instancetype)shared {
    static LCProxyConfig *instance;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        instance = [[LCProxyConfig alloc] init];
    });
    return instance;
}

- (NSString *)dataDirectory {
    return LCProxyDataDirectory();
}

- (NSString *)settingsPath {
    return [self.dataDirectory stringByAppendingPathComponent:LCProxySettingsFile];
}

- (NSString *)proxychainsConfPath {
    return [self.dataDirectory stringByAppendingPathComponent:LCProxyConfFile];
}

- (NSDictionary *)defaults {
    return @{
        @"proxyEnabled": @YES,
        @"blockNonTcp": @NO,
        @"proxyMode": @"custom",
        @"proxyType": @"http",
        @"proxyHost": @"127.0.0.1",
        @"proxyPort": @8080,
        @"kingUpstreamHost": @"157.148.54.212",
        @"kingUpstreamPort": @8091,
        @"kingRefreshURL": @"http://kc.iikira.com/kingcard",
        @"kingGuidOverride": [NSNull null],
        @"kingTokenOverride": [NSNull null],
    };
}

- (NSDictionary *)load {
    NSData *data = [NSData dataWithContentsOfFile:self.settingsPath];
    if (!data) return [self defaults];
    id obj = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
    if (![obj isKindOfClass:[NSDictionary class]]) return [self defaults];
    NSMutableDictionary *merged = [NSMutableDictionary dictionaryWithDictionary:[self defaults]];
    for (NSString *key in [self defaults]) {
        id v = obj[key];
        if (v) merged[key] = v;
    }
    return merged;
}

- (BOOL)saveSettings:(NSDictionary *)settings {
    NSMutableDictionary *merged = [NSMutableDictionary dictionaryWithDictionary:[self defaults]];
    for (NSString *key in [self defaults]) {
        id v = settings[key];
        if (v) merged[key] = v;
    }
    NSError *err = nil;
    if (![[NSFileManager defaultManager] createDirectoryAtPath:self.dataDirectory
                                  withIntermediateDirectories:YES attributes:nil error:&err]) {
        return NO;
    }
    NSData *data = [NSJSONSerialization dataWithJSONObject:merged options:NSJSONWritingPrettyPrinted error:&err];
    if (!data || ![data writeToFile:self.settingsPath options:NSDataWritingAtomic error:&err]) {
        return NO;
    }
    return [self writeProxychainsConf:merged];
}

- (BOOL)writeProxychainsConf:(NSDictionary *)settings {
    NSString *mode = [settings[@"proxyMode"] isKindOfClass:[NSString class]] ? settings[@"proxyMode"] : @"custom";
    NSString *type = @"http";
    NSString *host = @"127.0.0.1";
    NSInteger port = 8080;
    if ([mode isEqualToString:@"kingcard"]) {
        // Local KingCard forwarder: handles token fetch + Q-GUID/Q-Token headers.
        host = @"127.0.0.1";
        port = 18080;
    } else {
        type = [settings[@"proxyType"] isKindOfClass:[NSString class]] ? settings[@"proxyType"] : @"http";
        host = [settings[@"proxyHost"] isKindOfClass:[NSString class]] && [settings[@"proxyHost"] length] ? settings[@"proxyHost"] : @"127.0.0.1";
        port = [settings[@"proxyPort"] respondsToSelector:@selector(integerValue)] ? [settings[@"proxyPort"] integerValue] : 8080;
        if (port <= 0 || port > 65535) port = 8080;
    }
    NSMutableString *conf = [NSMutableString string];
    [conf appendString:@"# Generated by LCProxyControl. Edit from the console app.\n"];
    [conf appendString:@"dynamic_chain\n"];
    [conf appendString:@"[ProxyList]\n"];
    [conf appendFormat:@"%@ %@ %ld\n", type, host, (long)port];
    NSError *err = nil;
    return [conf writeToFile:self.proxychainsConfPath atomically:YES encoding:NSUTF8StringEncoding error:&err];
}

- (void)applyToRuntime {
    NSDictionary *s = [self load];
    BOOL enabled = [s[@"proxyEnabled"] boolValue];
    BOOL block = [s[@"blockNonTcp"] boolValue];
    lcproxy_control_set_enabled(enabled ? 1 : 0);
    lcproxy_control_set_block_non_tcp(block ? 1 : 0);
    [[LCProxyKing shared] applyConfig:s];
}

@end
